from django.db import models


class Recipe(models.Model):
    title = models.TextField()
    price_per_serving = models.FloatField()
    weight_per_serving = models.IntegerField()
    vegetarian = models.BooleanField()
    vegan = models.BooleanField()
    gluten_free = models.BooleanField()
    dairy_free = models.BooleanField()
    sustainable = models.BooleanField()
    very_healthy = models.BooleanField()
    very_popular = models.BooleanField()
    gaps = models.CharField(max_length=50)
    low_fodmap = models.BooleanField()
    ketogenic = models.BooleanField()
    whole30 = models.BooleanField()
    ready_in_minutes = models.IntegerField()
    spoonacular_sourceUrl = models.URLField()
    image = models.CharField(max_length=255)


    aggregate_likes = models.IntegerField()
    spoonacular_score = models.IntegerField()
    health_score = models.IntegerField()
    percent_protein = models.FloatField()
    percent_fat = models.FloatField()
    percent_carbs = models.FloatField()
    dish_types = models.TextField()
    ingredients = models.TextField()
    cuisines = models.TextField()
    calories = models.FloatField()
    fat_g = models.FloatField()
    saturated_fat_g = models.FloatField()
    carbohydrates_g = models.FloatField()
    sugar_g = models.FloatField()
    cholesterol_mg = models.FloatField()
    sodium_mg = models.FloatField()
    protein_g = models.FloatField()
    vitamin_B3_mg = models.FloatField()
    selenium_microg = models.FloatField()
    Phosphorus_mg = models.FloatField()
    Iron_mg = models.FloatField()
    vitamin_B2_mg = models.FloatField()
    calcium_mg = models.FloatField()
    vitamin_B1_mg = models.FloatField()
    folate_microg = models.FloatField()
    potassium_mg = models.FloatField()
    copper_mg = models.FloatField()
    zinc_mg = models.FloatField()
    Manganese_mg = models.FloatField()
    Magnesium_mg = models.FloatField()
    vitamin_B12_microg = models.FloatField()
    vitamin_B5_mg = models.FloatField()
    vitamin_B6_mg = models.FloatField()
    vitamin_E_mg = models.FloatField()
    Fiber_g = models.FloatField()
    vitamin_A_IU = models.FloatField()
    vitamin_D_microg = models.FloatField()
    vitamin_K_microg = models.FloatField()
    vitamin_C_mg = models.FloatField()
    alcohol_g = models.FloatField()
    caffeine_g = models.FloatField()



