version: "2.0"
services:
  django:
    container_name: cookix
    image: cookix/cookix:1.0
    build: ./build
    #command: gunicorn cookix_website.wsgi:application -b :8000
    command: python manage.py runserver 0.0.0.0:8000
    #restart: always
    volumes:
      - .:/code
      - django_admin:/usr/local/lib/python3.8/site-packages/django/contrib/admin/static
    ports:
      - "8000:8000"
volumes:
  django_admin:
