# Generated by Django 3.0 on 2021-04-07 17:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPreferences',
            fields=[
                ('user_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('vegetables', models.CharField(default='true', max_length=4)),
                ('gluten', models.CharField(default='true', max_length=4)),
                ('dairy', models.CharField(default='true', max_length=4)),
                ('pork', models.CharField(default='true', max_length=4)),
                ('oven', models.CharField(default='true', max_length=4)),
                ('microwave', models.CharField(default='true', max_length=4)),
                ('blender', models.CharField(default='true', max_length=4)),
            ],
        ),
    ]
