# Generated by Django 3.0 on 2021-03-12 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('price_per_serving', models.FloatField()),
                ('vegetarian', models.TextField()),
                ('vegan', models.TextField()),
                ('gluten_free', models.TextField()),
                ('dairy_free', models.TextField()),
                ('sustainable', models.TextField()),
                ('very_healthy', models.TextField()),
                ('very_popular', models.TextField()),
                ('gaps', models.TextField()),
                ('low_fodmap', models.TextField()),
                ('ready_in_minutes', models.IntegerField()),
                ('spoonacular_sourceUrl', models.URLField()),
                ('image', models.TextField()),
                ('aggregate_likes', models.IntegerField()),
                ('spoonacular_score', models.IntegerField()),
                ('health_score', models.IntegerField()),
                ('dish_types', models.TextField()),
                ('ingredients', models.TextField()),
                ('cuisines', models.TextField()),
            ],
        ),
    ]
