# Generated by Django 3.1.5 on 2021-03-10 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('pricePerServing', models.CharField(max_length=255)),
                ('weightPerServing', models.CharField(max_length=255)),
                ('vegetarian', models.CharField(max_length=255)),
                ('vegan', models.CharField(max_length=255)),
                ('glutenFree', models.CharField(max_length=255)),
                ('dairyFree', models.CharField(max_length=255)),
                ('sustainable', models.CharField(max_length=255)),
                ('veryHealthy', models.CharField(max_length=255)),
                ('veryPopular', models.CharField(max_length=255)),
                ('gaps', models.CharField(max_length=255)),
                ('lowFodmap', models.CharField(max_length=255)),
                ('ketogenic', models.CharField(max_length=255)),
                ('whole30', models.CharField(max_length=255)),
                ('readyInMinutes', models.CharField(max_length=255)),
                ('spoonacularSourceUrl', models.CharField(max_length=255)),
                ('image', models.CharField(max_length=255)),
                ('aggregateLikes', models.CharField(max_length=255)),
                ('spoonacularScore', models.CharField(max_length=255)),
                ('healthScore', models.CharField(max_length=255)),
                ('percentProtein', models.CharField(max_length=255)),
                ('percentFat', models.CharField(max_length=255)),
                ('percentCarbs', models.CharField(max_length=255)),
                ('dishTypes', models.CharField(max_length=255)),
                ('ingredients', models.CharField(max_length=255)),
                ('cuisines', models.CharField(max_length=255)),
                ('calories', models.CharField(max_length=255)),
            ],
        ),
    ]
