# Generated by Django 3.0 on 2021-03-12 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='equipments',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='recipe',
            name='steps',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='recipe',
            name='summary',
            field=models.TextField(blank=True),
        ),
    ]
