# Generated by Django 3.0 on 2021-03-14 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_auto_20210312_2013'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='users_dislikes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='recipe',
            name='users_likes',
            field=models.IntegerField(default=0),
        ),
    ]
