# Generated by Django 3.0 on 2021-05-06 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0006_comments'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comments',
            old_name='dislike_date',
            new_name='comment_date',
        ),
    ]
